version: 2

references:

  ## Cache
  cache_paths: &cache_paths
    paths:
      - ~/work/.gradle
      - ~/.gradle
      - ~/.m2

  cache_key: &cache_key
    key: deps-{{ checksum "build.gradle" }}-{{ checksum "collect_app/build.gradle" }}

  cache_tests_key: &cache_tests_key
    key: test-deps-{{ checksum "build.gradle" }}-{{ checksum "collect_app/build.gradle" }}

  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key

  restore_tests_cache: &restore_tests_cache
    restore_cache:
      <<: *cache_tests_key

  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      <<: *cache_paths

  save_tests_cache: &save_tests_cache
    save_cache:
      <<: *cache_tests_key
      <<: *cache_paths

  accept_licenses : &accept_licenses
    run:
      name: Accept licenses
      command: yes | sdkmanager --licenses || true

  ## Workspace

  workspace: &workspace
    ~/work
  attach_debug_workspace: &attach_debug_workspace
    attach_workspace:
      at: *workspace
  persist_debug_workspace: &persist_debug_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - collect_app/build/outputs/androidTest-results
        - collect_app/build/outputs/apk
        - collect_app/build/outputs/code-coverage
        - collect_app/build/test-results
  attach_firebase_workspace: &attach_firebase_workspace
    attach_workspace:
      at: *workspace
  persist_firebase_workspace: &persist_firebase_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - firebase

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    environment:
#        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms1536m -Xmx4096m -XX:+HeapDumpOnOutOfMemoryError"'
#        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms1536m -Xmx4096m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.parallel=true'
        GRADLE_OPTS: '-Dorg.gradle.parallel=true'
    docker:
      - image: circleci/android:api-27-alpha
  gcloud_config: &gcloud_config
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest

jobs:

  ## Build debug APK and instrumented test APK

  build_debug:
    <<: *android_config
    steps:
        - checkout
        - *restore_cache
        - *accept_licenses
        - run:
            name: Download dependencies
            command: ./gradlew androidDependencies
        # Run code quality checks
        - run: ./gradlew pmd
        - run: ./gradlew checkstyle
        - run: ./gradlew lint
        - run: ./gradlew findbugs --stacktrace
        - *save_cache
        - store_artifacts:
            path: collect_app/build/reports
            destination: reports
        - run:
            name: Assemble debug build
            command: |
                ./gradlew assembleDebug -PdisablePreDex
        - run:
            name: Assemble test build
            command: |
                ./gradlew assembleDebugAndroidTest -PdisablePreDex
        - *persist_debug_workspace

  ## Run unit tests

  test_unit:
    <<: *android_config
    steps:
        - checkout
        - *restore_cache
##      Perhaps we should remove the above restoration since the below one includes it?
        - *restore_tests_cache
        - *accept_licenses
        - run:
            name: Download dependencies
            command: ./gradlew androidDependencies
        - run:
            name: Run unit tests
            command: ./gradlew testDebugUnitTest
        - *save_tests_cache
        - *persist_debug_workspace
        - store_artifacts:
            path: collect_app/build/reports
            destination: reports
        - store_test_results:
            path: collect_app/build/test-results

  ## Run instrumented tests

  test_instrumented:
    <<: *gcloud_config
    steps:
      - *attach_debug_workspace
      - run:
          name: Authorize gcloud
          command: |
            if [[ "$CIRCLE_PROJECT_USERNAME" == "opendatakit" ]]; then \
              gcloud config set project api-project-322300403941
              echo $GCLOUD_SERVICE_KEY | base64 --decode > client-secret.json
              gcloud auth activate-service-account --key-file client-secret.json
            fi
      - run:
          name: Run integration tests
          command: |
            if [[ "$CIRCLE_PROJECT_USERNAME" == "opendatakit" ]]; then \
              echo "y" | gcloud firebase test android run \
              --type instrumentation \
              --app collect_app/build/outputs/apk/debug/*.apk \
              --test collect_app/build/outputs/apk/androidTest/debug/*.apk \
              --device model=Nexus5,version=21,locale=en,orientation=portrait \
              --results-bucket opendatakit-collect-test-results \
              --environment-variables coverage=true,coverageFile=/sdcard/coverage.ec \
              --directories-to-pull /sdcard --timeout 20m
            fi
      - run:
          name: Copy integration test results
          command: |
            if [[ "$CIRCLE_PROJECT_USERNAME" == "opendatakit" ]]; then \
              mkdir firebase
              gsutil -m cp -r -U "`gsutil ls gs://opendatakit-collect-test-results | tail -1`*" /root/work/firebase/ | true
            fi
      - *persist_firebase_workspace
      - store_test_results:
          path: firebase/
          destination: /firebase/

  ## Submit JaCoCo coverage report

  report_coverage:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - *attach_debug_workspace
      - *attach_firebase_workspace
      - run:
          name: Move Firebase coverage report
          command: |
            if [[ "$CIRCLE_PROJECT_USERNAME" == "opendatakit" ]]; then \
              mkdir -p collect_app/build/outputs/code-coverage/connected && cp firebase/Nexus5-21-en-portrait/artifacts/coverage.ec collect_app/build/outputs/code-coverage/connected/coverage.ec
            fi
      - run:
          name: Generate JaCoCo report
          command: ./gradlew -PciBuild=true jacocoTestReport
      - run:
          name: Upload coverage report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: collect_app/build/reports/
          destination: /reports/

workflows:
  version: 2
  workflow:
    jobs:
      # This job will run on every commit on the master branch
      - build_debug:
          filters:
            branches:
              only: /^.*$/
              #only: /(master|(COLLECT)\-([0-9])+(.*))/
      # Unit tests should only start after a successful build. Or vice versa?
      - test_unit:
          requires:
            - build_debug
          filters:
            branches:
              only: /^.*$/
      # Instrumentation tests should only start after unit tests complete gracefully. Or vice versa?
      - test_instrumented:
          requires:
            - test_unit
          # We'd like to also filter by username and remove the if/fi above, but username filtering is not supported in CircleCI
          filters:
            branches:
              only: master
      - report_coverage:
          requires:
            - test_unit
            - test_instrumented
          # We'd like to also filter by username and remove the if/fi above, but username filtering is not supported in CircleCI
          filters:
            branches:
              only: master